[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.zksync]
src = 'src'
libs = ['lib']
fallback_oz = true
is_system = false
mode = "3"

[rpc_endpoints]
lens = "https://sepolia.rpc.lens.dev"
